db:
  uat:
    driver: RPostgres::Postgres
    args:
      dbname: montagu
      host: support.montagu.dide.ic.ac.uk
      port: 15432
      user: import
      password: import
    log_table: dettl_import_log
  science:
    driver: RPostgres::Postgres
    args:
      dbname: montagu
      host: support.montagu.dide.ic.ac.uk
      port: 5432
      user: import
      password: VAULT:/secret/vimc/database/science/users/import:password
    log_table: dettl_import_log
  latest:
    driver: RPostgres::Postgres
    args:
      dbname: montagu
      host: support.montagu.dide.ic.ac.uk
      port: 35432
      user: import
      password: VAULT:/secret/vimc/database/science/users/import:password
    log_table: dettl_import_log
  production:
    driver: RPostgres::Postgres
    args:
      dbname: montagu
      host: montagu.vaccineimpact.org
      port: 5432
      user: readonly
      password: VAULT:/secret/vimc/database/production/users/readonly:password
    log_table: dettl_import_log
    confirm: true

vault_server: https://vault.dide.ic.ac.uk:8200
